tabPanel("Attribution",
         tags$head(tags$style('table {font-size:13px;}')),
         sidebarPanel(
           style = "position:fixed; margin-top:80px; width:400px",
           HTML("# Default Data<br>Rp : portfolio returns<br>wp : portfolio weights<br>Rb : benchmark returns<br>wb : benchmark weights"),
           br(),br(),
           prettyRadioButtons(inputId = "method",
                              label = "priority between allocation and selection effects",
                              choices = list("none"="none",
                                             "top.down"="top.down",
                                             "bottom.up" = "bottom.up"), 
                              selected = "none"),
           prettyRadioButtons(inputId = "linking",
                              label = "linking method to present the multi-period summary",
                              choices = list("carino"="carino",
                                             "menchero"="menchero",
                                             "grap"="grap",
                                             "frongello"="frongello",
                                             "davies.laker" = "davies.laker"), 
                              selected = "carino"),
           prettyRadioButtons(inputId = "bf",
                              label = "methodology",
                              choices = list("Brinson-Fachler"="TRUE",
                                             "Brinson–Hood–Beebower"="FALSE"), 
                              selected = "FALSE"),
           prettyRadioButtons(inputId = "geometric",
                              label = "geometric or arithmetic excess returns",
                              choices = list("geometric"="TRUE",
                                             "arithmetic"="FALSE"), 
                              selected = "FALSE"),
           prettyRadioButtons(inputId = "adjusted",
                              label = "original or smoothed attribution effects",
                              choices = list("adjusted"="TRUE",
                                             "unadjusted"="FALSE"), 
                              selected = "FALSE")
           # fileInput(inputId = 'wpf',
           #           label = 'portfolio weights of currency forward contracts',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'wbf',
           #           label = 'benchmark weights of currency forward contracts',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'S',
           #           label = 'spot rates',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'F',
           #           label = 'forward rates',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'Rpl',
           #           label = 'portfolio returns in local currency',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'Rbl',
           #           label = 'benchmark returns in local currency',
           #           buttonLabel = "upload"),
           # fileInput(inputId = 'Rbh',
           #           label = 'benchmark returns hedged into the base currency',
           #           buttonLabel = "upload")
         ),
         mainPanel(
           style = "margin-left:450px; margin-top:80px",
           tabsetPanel(
             type = "tabs",
             tabPanel("attribution",
                      br(),
                      HTML("<font color=red><b><big><u> - Excess returns </u></big></b></font>"),
                      highchartOutput("ExcessReturnsLineChart", height = "300px"),
                      DT::dataTableOutput("ExcessReturns"),
                      hr(),
                      HTML("<font color=red><b><big><u> - Attribution </u></big></b></font>"),
                      highchartOutput("AttributionAreaChart", height = "400px"),
                      hr(),
                      # highchartOutput("AllocationPieChart"),
                      DT::dataTableOutput("Allocation"),
                      br(),
                        DT::dataTableOutput("Selection"),
                      br(),
                      DT::dataTableOutput("Interaction"),
                      br()
             ),
             tabPanel("Sample Data",
                      br(),
                      HTML("<font color=red><b><big> - portfolio returns</big></b></font>"),
                      tableOutput("Rp"),
                      hr(),
                      HTML("<font color=red><b><big> - portfolio weights</big></b></font>"),
                      tableOutput("wp"),
                      hr(),
                      HTML("<font color=red><b><big> - benchmark returns</big></b></font>"),
                      tableOutput("Rb"),
                      hr(),
                      HTML("<font color=red><b><big> - benchmark weights</big></b></font>"),
                      tableOutput("wb"),
                      br()
             ),
             tabPanel("Raw Data",
                      br(),
                      HTML("<font color=red><b><big> - returns</big></b></font>"),
                      DT::dataTableOutput("returns"),
                      hr(),
                      HTML("<font color=red><b><big> - weights</big></b></font>"),
                      DT::dataTableOutput("weights"),
                      hr(),
                      HTML("<font color=red><b><big> - hierarchy</big></b></font>"),
                      DT::dataTableOutput("hierarchy"),
                      hr(),
                      HTML("<font color=red><b><big> - allocation</big></b></font>"),
                      DT::dataTableOutput("allocation"),
                      hr(),
                      HTML("<font color=red><b><big> - currency</big></b></font>"),
                      DT::dataTableOutput("currency"),
                      br()
             ),
             tabPanel("Description",
                      includeMarkdown('attribution_description.Rmd'))
           )
         )
)